const fs = require('fs');

const routeMap = JSON.parse(fs.readFileSync('tests/e2e/discovery/route_map.json', 'utf8'));

// Phase 3 - Full Suite
let fullSuiteTs = `// AUTO-GENERATED by Universal QA Agent
// App: process.env.APP_URL
// Generated: ${new Date().toISOString()}
// Total scenarios: ${Object.keys(routeMap).length * 4}
// Safe mode: process.env.SAFE_MODE
// Destructive security tests: process.env.RUN_DESTRUCTIVE_SECURITY_TESTS

import { test, expect, Page, BrowserContext } from '@playwright/test';
import { Selectors } from './selectors';

const APP_URL = process.env.APP_URL ?? 'https://frontend-manojsilwals-projects.vercel.app';
const API_URL = process.env.API_URL ?? 'http://localhost:8000';
const TEST_USER_EMAIL = process.env.TEST_USER_EMAIL ?? 'demo@app.test';
const TEST_USER_PASSWORD = process.env.TEST_USER_PASSWORD ?? 'TestPass123!';
const TEST_SECOND_USER_EMAIL = process.env.TEST_SECOND_USER_EMAIL ?? 'victim@app.test';
const TEST_SECOND_USER_PASSWORD = process.env.TEST_SECOND_USER_PASSWORD ?? 'TestPass123!';
const TEST_RUN_ID = process.env.TEST_RUN_ID ?? \`qa_\${Date.now()}\`;
const RUN_DESTRUCTIVE_SECURITY_TESTS = process.env.RUN_DESTRUCTIVE_SECURITY_TESTS === 'true';
const SAFE_MODE = process.env.SAFE_MODE !== 'false';

async function attachConsoleCapture(page: Page) {
  const errors: string[] = [];

  page.on('console', msg => {
    if (msg.type() === 'error') {
       if (!msg.text().includes('Failed to load resource')) {
           errors.push(msg.text());
       }
    }
  });

  page.on('pageerror', err => {
    errors.push(err.message);
  });

  return {
    errors,
    assertNoErrors: () => {
       expect(errors).toEqual([]);
    },
  };
}

async function assertNoXss(page: Page) {
  const xssTriggered = await page.evaluate(() => (window as any).__xss);
  expect(xssTriggered).toBeUndefined();
}

test.beforeEach(async ({ page }) => {
  await page.goto(APP_URL);
  try {
     // Check if the skip tour button exists and is visible
     const skipBtn = Selectors.common.skipTourButton(page);
     if (await skipBtn.isVisible({ timeout: 2000 })) {
       await skipBtn.click();
       await page.waitForTimeout(500); // Wait for transition
     }
  } catch (e) {
     // no tour to skip
  }
});

`;

const featureKeys = {
  "/": "dashboard",
  "/macro": "macro",
  "/gold": "gold",
  "/chat": "chat",
  "/debate": "debate",
  "/backtest": "backtest",
  "/scorecard": "scorecard",
  "/challenge": "challenge",
  "/portfolio": "portfolio",
  "/learning": "learning",
  "/observer": "observer",
  "/systemmap": "systemmap",
  "/system-diagrams": "systemdiagrams"
};

for (const route in routeMap) {
  const feature = route === '/' ? 'DASHBOARD' : route.substring(1).toUpperCase().replace('-', '_');
  const path = route;
  const navKey = featureKeys[route];

  fullSuiteTs += `
test.describe('${feature}', () => {
  test('${feature}-HP-001 — Navigation loads ${route}', async ({ page }) => {
    const consoleCapture = await attachConsoleCapture(page);

    if ('${route}' !== '/') {
      const navBtn = Selectors.nav.${navKey}(page);
      if (await navBtn.isVisible()) {
          await navBtn.click();
          await page.waitForURL(new RegExp(\`\${APP_URL}${path}\`), { timeout: 10000 });
      } else {
          // Fallback if not visible
          await page.goto(\`\${APP_URL}${path}\`);
      }
    } else {
      await page.goto(\`\${APP_URL}${path}\`);
    }

    await expect(page).toHaveURL(new RegExp(\`\${APP_URL}${path}\`));
    consoleCapture.assertNoErrors();
  });

  test('${feature}-HP-002 — Page title is correct', async ({ page }) => {
    await page.goto(\`\${APP_URL}${path}\`);
    await expect(page).toHaveTitle(/TradeTalk/i);
  });

  test('${feature}-NEG-001 — Handles non-existent nested route safely', async ({ page }) => {
    const consoleCapture = await attachConsoleCapture(page);
    await page.goto(\`\${APP_URL}${path}/doesnotexist\`);
    // ASSUMPTION: The app handles 404s gracefully by falling back or showing standard layout.
    await expect(page).toHaveURL(/doesnotexist/);
    consoleCapture.assertNoErrors();
  });

  test('${feature}-SEC-001 — No XSS via URL params', async ({ page }) => {
    const consoleCapture = await attachConsoleCapture(page);
    await page.goto(\`\${APP_URL}${path}?search=<script>window.__xss=1</script>\`);
    await assertNoXss(page);
    consoleCapture.assertNoErrors();
  });
});
`;
}

fs.writeFileSync('tests/e2e/full_suite.spec.ts', fullSuiteTs);

console.log("Phase 3 regenerated");
