services:
  - type: web
    name: tradetalkapp-backend
    runtime: python
    rootDir: k2_optimus
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn k2_optimus.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
