// AUTO-GENERATED by Universal QA Agent — Phase 2

// Do not edit manually. Re-run agent to regenerate.

import { Page } from '@playwright/test';

export const Selectors = {
  nav: {
    dashboard: (page: Page) => page.getByRole('button', { name: /Dashboard/i }),
    macro: (page: Page) => page.getByRole('button', { name: /Macro/i }),
    gold: (page: Page) => page.getByRole('button', { name: /Gold/i }),
    chat: (page: Page) => page.getByRole('button', { name: /Chat/i }),
    debate: (page: Page) => page.getByRole('button', { name: /Debate/i }),
    backtest: (page: Page) => page.getByRole('button', { name: /Backtest/i }),
    scorecard: (page: Page) => page.getByRole('button', { name: /Scorecard/i }),
    challenge: (page: Page) => page.getByRole('button', { name: /Challenge/i }),
    portfolio: (page: Page) => page.getByRole('button', { name: /Portfolio/i }),
    learning: (page: Page) => page.getByRole('button', { name: /Learning/i }),
    observer: (page: Page) => page.getByRole('button', { name: /Observer/i }),
    systemmap: (page: Page) => page.getByRole('button', { name: /Systemmap/i }),
    systemdiagrams: (page: Page) => page.getByRole('button', { name: /System Diagrams/i }),
  }
};
