// AUTO-GENERATED by Universal QA Agent — Phase 2
// Do not edit manually. Re-run agent to regenerate.

import { Page } from '@playwright/test';

export const Selectors = {
  common: {
    skipTourButton: (page: Page) => page.getByRole('button', { name: /Skip tour/i }),
  },
  nav: {
    dashboard: (page: Page) => page.locator('button').filter({ hasText: /^Dashboard$/ }),
    macro: (page: Page) => page.locator('button').filter({ hasText: /^Global Macro$/ }),
    gold: (page: Page) => page.locator('button').filter({ hasText: /^Gold Advisor$/ }),
    chat: (page: Page) => page.locator('button').filter({ hasText: /^Assistant$/ }),
    debate: (page: Page) => page.locator('button').filter({ hasText: /^AI Debate$/ }),
    backtest: (page: Page) => page.locator('button').filter({ hasText: /^Strategy Lab$/ }),
    scorecard: (page: Page) => page.locator('button').filter({ hasText: /^Risk\/Return Scorecard$/ }),
    challenge: (page: Page) => page.locator('button').filter({ hasText: /^Daily Challenge$/ }),
    portfolio: (page: Page) => page.locator('button').filter({ hasText: /^Paper Portfolio$/ }),
    learning: (page: Page) => page.locator('button').filter({ hasText: /^Learning Path$/ }),
    observer: (page: Page) => page.locator('button').filter({ hasText: /^Developer Trace$/ }),
    systemmap: (page: Page) => page.locator('button').filter({ hasText: /^System Map$/ }),
    systemdiagrams: (page: Page) => page.locator('button').filter({ hasText: /^System Diagrams$/ }),
  }
};
