-- Add new revenue engine score columns to stocks
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS financial_traction_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS customer_adoption_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS management_commitment_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS market_opportunity_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS monetization_clarity_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS execution_capacity_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS new_revenue_engine_score DOUBLE PRECISION DEFAULT NULL;
