"""TradeTalk Finance Brain.

A model-agnostic financial intelligence engine: features -> labels -> models ->
backtest -> ranking/inference, with an LLM explanation layer that is grounded in
structured model output (it never invents numbers).

This package is additive and self-contained. It does not modify any existing
TradeTalk module; it is the strangler-fig "brain" that the rest of the app can
adopt incrementally (see docs/finance-brain-architecture.html).

Hard rules enforced in code (see docs Section 08):
  - No model output without ``model_version`` and ``as_of_date``.
  - No claim of certainty: outputs are probabilities + confidence.
  - LLM numbers are verified against the structured payload (agent_explainer).
"""
from __future__ import annotations

DISCLAIMER = (
    "This output is generated by quantitative models and AI agents for research "
    "purposes only. It is not financial advice, investment advice, or a "
    "recommendation to buy or sell securities. Model predictions may be wrong and "
    "should be independently verified."
)

# Default prediction horizon (trading days) and the canonical feature contract.
# 63 trading days (~1 quarter) stays the fast self-learning-loop label so graded
# outcomes accrue in weeks (SEPL fixtures, conformal recalibration, learned
# weights all depend on this cadence — see docs/PHASE_HARNESS_SUPERINVESTOR.md).
DEFAULT_HORIZON_DAYS = 63

# Investment-surface horizons (trading days). These power the long-horizon
# investment surface (1/3/5-year reasoning) WITHOUT replacing the 63-day learning
# label — they are additive. ~252 trading days ≈ 1 calendar year.
TRADING_DAYS_PER_YEAR = 252
MIN_INVESTMENT_HORIZON_MONTHS = 12
INVESTMENT_HORIZON_DAYS = {
    "1y": 252,
    "3y": 756,
    "5y": 1260,
}

# The ordered feature list the v1 brain trains/serves on. Immutable per model
# version (the model registry stores the exact list it was trained with).
FEATURE_LIST = [
    "return_1m",
    "return_3m",
    "return_6m",
    "return_12m",
    "volatility_3m",
    "volatility_6m",
    "max_drawdown_6m",
    "relative_strength_3m",
    "relative_strength_6m",
    "price_vs_50dma",
    "price_vs_200dma",
    "revenue_growth_yoy",
    "gross_margin",
    "operating_margin",
    "net_margin",
    "fcf_margin",
    "roic",
    "debt_to_equity",
    "fcf_yield",
    "pe_ratio",
    "ev_ebitda",
    "valuation_percentile_5y",
    "capital_flow_score",
    "institutional_accumulation_score",
    "filing_risk_score",
    "customer_concentration_score",
    "new_product_expansion_score",
    "management_tone_score",
    "sentiment_score",
    # TimesFM time-series head (reuses backend/predictor/). Forward-looking
    # features derived from probabilistic price-path quantiles.
    "tsfm_expected_return",
    "tsfm_band_width",
]

# Signal groups surfaced to the UI (0-100 scores). Maps feature groups -> label.
SIGNAL_GROUPS = (
    "momentum",
    "quality",
    "valuation",
    "capital_flow",
    "filing_intelligence",
    "sentiment",
    "risk",
    "timeseries",
)

__all__ = [
    "DISCLAIMER",
    "DEFAULT_HORIZON_DAYS",
    "TRADING_DAYS_PER_YEAR",
    "MIN_INVESTMENT_HORIZON_MONTHS",
    "INVESTMENT_HORIZON_DAYS",
    "FEATURE_LIST",
    "SIGNAL_GROUPS",
]
