"""
Phase 6 — Upload condensed RAG summaries to Supabase (pgvector) or ChromaDB.

Reads the all_summaries.json generated by summarize_for_rag.py and pushes
each document into the appropriate vector collection via the existing
KnowledgeStore / VectorBackend infrastructure.

This script reuses the project's existing vector_backends.py so it works
with both ChromaDB (local) and Supabase (remote) depending on env vars.

Usage:
    python -m backend.data_lake.upload_to_supabase --dry-run
    python -m backend.data_lake.upload_to_supabase --batch-size 100
    python -m backend.data_lake.upload_to_supabase
"""
import argparse
import json
import logging
import os
import sys
import time

from . import config

logger = logging.getLogger(__name__)

DEFAULT_BATCH_SIZE = 50


def _get_vector_backend():
    """Instantiate the appropriate vector backend from env vars."""
    backend_type = os.environ.get("VECTOR_BACKEND", "chroma").lower()
    if backend_type == "supabase":
        url = os.environ.get("SUPABASE_URL", "")
        key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
        if not url or not key:
            logger.error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY required for supabase backend")
            sys.exit(1)
        from backend.vector_backends import SupabaseVectorBackend
        return SupabaseVectorBackend(url, key), "supabase"
    else:
        chroma_path = os.environ.get("CHROMA_PATH", "./chroma_db")
        from backend.vector_backends import ChromaVectorBackend
        return ChromaVectorBackend(chroma_path), "chroma"


def run(dry_run: bool = False, batch_size: int = DEFAULT_BATCH_SIZE) -> dict:
    """Load summaries from disk and push to vector store."""
    summaries_path = os.path.join(config.SUMMARIES_DIR, "all_summaries.json")

    if not os.path.exists(summaries_path):
        logger.error("No summaries found at %s. Run summarize_for_rag first.", summaries_path)
        return {"error": "no summaries file", "uploaded": 0}

    with open(summaries_path, "r") as f:
        summaries = json.load(f)

    logger.info("Loaded %d summaries from %s", len(summaries), summaries_path)

    # Group by collection
    by_collection: dict[str, list[dict]] = {}
    for s in summaries:
        col = s.get("collection", "unknown")
        by_collection.setdefault(col, []).append(s)

    for col, items in by_collection.items():
        logger.info("  %s: %d documents", col, len(items))

    if dry_run:
        logger.info("[DRY RUN] Would upload %d documents to %d collections",
                     len(summaries), len(by_collection))
        return {"dry_run": True, "total": len(summaries), "collections": list(by_collection.keys())}

    backend, backend_name = _get_vector_backend()
    logger.info("Using vector backend: %s", backend_name)

    uploaded = 0
    errors = []

    for col_name, items in by_collection.items():
        backend.ensure_collection(col_name)

        for i in range(0, len(items), batch_size):
            batch = items[i : i + batch_size]
            docs = [s["document"] for s in batch]
            metas = [s.get("metadata", {}) for s in batch]
            ids = [s["id"] for s in batch]

            # Sanitize metadata values for Chroma (must be str/int/float/bool)
            for m in metas:
                for k, v in list(m.items()):
                    if v is None:
                        m[k] = ""
                    elif isinstance(v, (list, dict)):
                        m[k] = json.dumps(v)

            try:
                backend.add(col_name, documents=docs, metadatas=metas, ids=ids)
                uploaded += len(batch)
            except Exception as e:
                logger.warning("Failed batch for %s: %s", col_name, e)
                errors.extend(ids)

            if i + batch_size < len(items):
                time.sleep(0.5)

        logger.info("  [%s] uploaded %d / %d", col_name, min(uploaded, len(items)), len(items))

    logger.info("Upload complete: %d uploaded, %d errors", uploaded, len(errors))
    return {"uploaded": uploaded, "errors": errors, "backend": backend_name}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="Upload RAG summaries to vector store")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    args = parser.parse_args()
    run(dry_run=args.dry_run, batch_size=args.batch_size)
